INSERT INTO
    `clients`(
        `razonsocial`,
        `pcontacto`,
        `telefono`,
        `email`,
        `direccion`,
        `created_at`,
        `updated_at`
    )
VALUES
    (
        'Social',
        'Pablo',
        '123456789',
        'pablo@gmail.com',
        'Arganda',
        'now()',
        'now()'
    ),
    (
        'Incomprendido',
        'JoseMa',
        '123456789',
        'josema@gmail.com',
        'Rivas',
        'now()',
        'now()'
    ),
    (
        'Quemado',
        'Marcos',
        '123456789',
        'marcos@gmail.com',
        'Arganda',
        'now()',
        'now()'
    )